config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  root to: 'pages#home'
  resources :municipes, except: %i[destroy]

  get '/up/', to: 'up#index', as: :up
  get '/up/databases', to: 'up#databases', as: :up_databases

  # Sidekiq has a web dashboard which you can enable below. It's turned off by
  # default because you very likely wouldn't want this to be available to
  # everyone in production.
  #
  # Uncomment the 2 lines below to enable the dashboard WITHOUT authentication,
  # but be careful because even anonymous web visitors will be able to see it!
  # require "sidekiq/web"
  # mount Sidekiq::Web => "/sidekiq"
  #
  # If you add Devise to this project and happen to have an admin? attribute
  # on your user you can uncomment the 4 lines below to only allow access to
  # the dashboard if you're an admin. Feel free to adjust things as needed.
  # require "sidekiq/web"
  # authenticate :user, lambda { |u| u.admin? } do
  #   mount Sidekiq::Web => "/sidekiq"
  # end

  # Learn more about this file at: https://guides.rubyonrails.org/routing.html
end

app/models/municipe.rb
# frozen_string_literal: true

class Municipe < ApplicationRecord
  include PgSearch::Model

  pg_search_scope :search_municipes,
                  against: %i[national_health_card cpf email],
                  using: {
                    tsearch: { prefix: true }
                  }

  # One-to-one association with Address. The address is automatically destroyed if the Municipe is deleted.
  has_one :address, dependent: :destroy

  # Allows creation/update of an associated address directly within a Municipe's form.
  accepts_nested_attributes_for :address

  # Validates the presence of essential attributes to ensure a Municipe record is complete.
  validates :first_name, :last_name, :cpf, :national_health_card, :birth_date,
            :phone_number, presence: true

  # Ensures CPF is unique and exactly 11 digits long, assuming CPF is stored without formatting.
  validates :cpf, uniqueness: true, length: { is: 11 }

  # Custom validation for the CPF to ensure it adheres to Brazil's CPF format and validity rules.
  validate :validate_cpf

  # Ensures the national health card and email are unique across all records.
  validates :national_health_card, uniqueness: true
  validates :email, uniqueness: true,
                    format: { with: URI::MailTo::EMAIL_REGEXP }

  # Validate min and max age
  validate :validate_age

  # Uses an enum for the 'status' field to neatly map the active (1) and inactive (0) states.
  enum status: { inactive: 0, active: 1 }

  # Validates that the associated address is also valid whenever a Municipe is saved.
  validates_associated :address

  has_one_attached :photo do |attachable|
    attachable.variant :thumb, resize_to_limit: [100, 100]
    attachable.variant :medium, resize_to_limit: [300, 300]
    attachable.variant :large, resize_to_limit: [600, 600]
  end

  private

  # Validates the CPF for correctness beyond just format, utilizing the 'cpf_cnpj' gem for comprehensive checks.
  def validate_cpf
    return if cpf.blank?
    # Strips non-numeric characters from CPF and checks validity.
    return if CPF.valid?(cpf.gsub(/[^0-9]/, ''), strict: true)

    errors.add(:cpf, 'is invalid')
  end

  def validate_age
    return if birth_date.blank?

    if birth_date > 18.years.ago.to_date
      errors.add(:birth_date, 'You must be at least 18 years old')
    elsif birth_date < 100.years.ago.to_date
      errors.add(:birth_date, 'Age seems to be invalid') # Mensagem de erro genérica; ajuste conforme necessário.
    end
  end
end

app/controllers/municipes_controller.rb
# frozen_string_literal: true

class MunicipesController < ApplicationController
  before_action :municipes, only: %i[index update create]
  before_action :municipe,  only: %i[show edit update]
  before_action :build_municipe, only: %i[new]

  include Pagy::Backend

  def index
    flash.keep if turbo_frame_request?
  end

  def show; end

  def edit; end

  def update
    operation = Operations::Municipes::Update.new(municipe_params)
    operation.object = @municipe
    operation.perform

    respond_to do |format|
      if operation.succeeded?
        format.turbo_stream { flash.now[:success] = 'Municipe updated' }
      else
        format.turbo_stream { flash.now[:danger] = 'Não foi possivel atualizar' }
      end
    end
  end

  def new; end

  def create
    operation = Operations::Municipes::Create.new(municipe_params)
    operation.perform

    respond_to do |format|
      if operation.succeeded?
        format.turbo_stream { flash.now[:success] = 'Municipe created' }
      else
        msg = operation.errors.messages
        format.turbo_stream { flash.now[:danger] = msg }
      end
    end
  end

  private

  def municipe
    @municipe = Municipe.find(params[:id])
  end

  # rubocop:disable Layout/LineLength, Lint/MissingCopEnableDirective
  def municipes
    if params[:query].present?
      @pagy, @municipes = pagy(Municipe.search_municipes(params[:query]).includes(:address), items: 5,
                                                                                              link_extra: 'data-turbo-frame="search"')
    else
      @pagy, @municipes = pagy(Municipe.includes(:address).all, items: 5,
                                                                link_extra: 'data-turbo-frame="search"')
    end
  end

  def build_municipe
    @municipe = Municipe.new
    @municipe.build_address
  end

  def municipe_params
    params.require(:municipe).permit(:first_name, :last_name, :cpf, :national_health_card,
                                    :email, :birth_date, :phone_number, :status, :photo,
                                    address_attributes: %i[street ibge_code neighborhood city state zip_code])
  end
end

app/views/municipes/_address_fields.html.erb
<%= form.fields_for :address do |address_fields| %>

  <div class="col-span-2 sm:col-span-1">
    <%= address_fields.label :zip_code, class: 'block mb-2 text-sm font-medium text-gray-900 dark:text-white' %>
    <%= address_fields.text_field :zip_code, class: 'bg-gray-50 border border-gray-300 text-gray-900 text-sm rounded-lg focus:ring-primary-600 focus:border-primary-600 block w-full p-2.5 dark:bg-gray-600 dark:border-gray-500 dark:placeholder-gray-400 dark:text-white dark:focus:ring-primary-500 dark:focus:border-primary-500', required: true %>
  </div>

  <div class="col-span-2 sm:col-span-1">
    <%= address_fields.label :street, class: 'block mb-2 text-sm font-medium text-gray-900 dark:text-white' %>
    <%= address_fields.text_field :street, class: 'bg-gray-50 border border-gray-300 text-gray-900 text-sm rounded-lg focus:ring-primary-600 focus:border-primary-600 block w-full p-2.5 dark:bg-gray-600 dark:border-gray-500 dark:placeholder-gray-400 dark:text-white dark:focus:ring-primary-500 dark:focus:border-primary-500', required: true %>
  </div>

  <div class="col-span-2 sm:col-span-1">
    <%= address_fields.label :ibge_code, class: 'block mb-2 text-sm font-medium text-gray-900 dark:text-white' %>
    <%= address_fields.text_field :ibge_code, class: 'bg-gray-50 border border-gray-300 text-gray-900 text-sm rounded-lg focus:ring-primary-600 focus:border-primary-600 block w-full p-2.5 dark:bg-gray-600 dark:border-gray-500 dark:placeholder-gray-400 dark:text-white dark:focus:ring-primary-500 dark:focus:border-primary-500' %>
  </div>

  <div class="col-span-2 sm:col-span-1">
    <%= address_fields.label :neighborhood, class: 'block mb-2 text-sm font-medium text-gray-900 dark:text-white' %>
    <%= address_fields.text_field :neighborhood, class: 'bg-gray-50 border border-gray-300 text-gray-900 text-sm rounded-lg focus:ring-primary-600 focus:border-primary-600 block w-full p-2.5 dark:bg-gray-600 dark:border-gray-500 dark:placeholder-gray-400 dark:text-white dark:focus:ring-primary-500 dark:focus:border-primary-500', required: true %>
  </div>

  <div class="col-span-2 sm:col-span-1">
    <%= address_fields.label :city, class: 'block mb-2 text-sm font-medium text-gray-900 dark:text-white' %>
    <%= address_fields.text_field :city, class: 'bg-gray-50 border border-gray-300 text-gray-900 text-sm rounded-lg focus:ring-primary-600 focus:border-primary-600 block w-full p-2.5 dark:bg-gray-600 dark:border-gray-500 dark:placeholder-gray-400 dark:text-white dark:focus:ring-primary-500 dark:focus:border-primary-500', required: true %>
  </div>

  <div class="col-span-2 sm:col-span-1">
    <%= address_fields.label :state, class: 'block mb-2 text-sm font-medium text-gray-900 dark:text-white' %>
    <%= address_fields.text_field :state, class: 'bg-gray-50 border border-gray-300 text-gray-900 text-sm rounded-lg focus:ring-primary-600 focus:border-primary-600 block w-full p-2.5 dark:bg-gray-600 dark:border-gray-500 dark:placeholder-gray-400 dark:text-white dark:focus:ring-primary-500 dark:focus:border-primary-500', required: true %>
  </div>
<% end %>

app/views/municipes/_address_info.html.erb
<% if address %>
  <p><%= address.street %>, <%= address.city %>, <%= address.state %>, <%= address.zip_code %></p>
<% else %>
  <p>No Address Provided</p>
<% end %>

app/views/municipes/_form.html.erb
<%= form_with model: municipe, class: 'p-4 md:p-5',
                              data: { action: 'turbo:submit-end->components--drawer-component#hideOnSuccess' } do |form| %>

  <h5 class="inline-flex items-center mb-6 text-sm font-semibold text-gray-500 uppercase dark:text-gray-400"> General Information </h5>

  <div id="flash">
    <%= render_flash_messages %>
  </div>

  <%= render partial: 'general_info_fields', locals: { form: form, municipe: municipe } %>

  <h5 class="inline-flex items-center mb-6 text-sm font-semibold text-gray-500 uppercase dark:text-gray-400"> Address Information </h5>

  <div class="grid gap-4 mb-4 grid-cols-2">
    <%= render partial: 'address_fields', locals: { form: form } %>
  </div>


 <div class="left-0 flex justify-center w-full pb-4 space-x-4 md:px-4 md:absolute">
    <%= form.submit class: 'btn-primary' %>
  </div>
<% end %>

app/views/municipes/_general_info_fields.html.erb
<div data-controller="previews">
  <div class="p-4 mb-4 bg-white border border-gray-200 rounded-lg shadow-sm 2xl:col-span-2 dark:border-gray-700 sm:p-6 dark:bg-gray-800">
    <div class="items-center sm:flex xl:block 2xl:flex sm:space-x-4 xl:space-x-0 2xl:space-x-4">
      <%= display_municipe_photo(municipe) %>
      <div>
        <h3 class="mb-1 text-xl font-bold text-gray-900 dark:text-white">Picture</h3>
        <div class="mb-4 text-sm text-gray-500 dark:text-gray-400">
            JPG, or PNG. Max size of Todo
        </div>
        <%= form.label :photo, class: 'inline-flex items-center btn btn-primary' do %>
          Select file
          <%= form.file_field :photo,  data: { previews_target: "input", action: "change->previews#preview" }, class: 'hidden' %>
        <% end %>
      </div>
    </div>
  </div>
</div>

<div class="grid gap-4 mb-4 grid-cols-2">
  <div class="col-span-2 sm:col-span-1">
    <%= form.label :first_name, class: 'block mb-2 text-sm font-medium text-gray-900 dark:text-white' %>
    <%= form.text_field :first_name, class: 'bg-gray-50 border border-gray-300 text-gray-900 text-sm rounded-lg focus:ring-primary-600 focus:border-primary-600 block w-full p-2.5 dark:bg-gray-600 dark:border-gray-500 dark:placeholder-gray-400 dark:text-white dark:focus:ring-primary-500 dark:focus:border-primary-500', required: true %>
  </div>

  <div class="col-span-2 sm:col-span-1">
    <%= form.label :last_name, class: 'block mb-2 text-sm font-medium text-gray-900 dark:text-white' %>
    <%= form.text_field :last_name, class: 'bg-gray-50 border border-gray-300 text-gray-900 text-sm rounded-lg focus:ring-primary-600 focus:border-primary-600 block w-full p-2.5 dark:bg-gray-600 dark:border-gray-500 dark:placeholder-gray-400 dark:text-white dark:focus:ring-primary-500 dark:focus:border-primary-500', required: true %>
  </div>

  <div class="col-span-2 sm:col-span-1">
    <%= form.label :cpf, class: 'block mb-2 text-sm font-medium text-gray-900 dark:text-white' %>
    <%= form.text_field :cpf, class: 'bg-gray-50 border border-gray-300 text-gray-900 text-sm rounded-lg focus:ring-primary-600 focus:border-primary-600 block w-full p-2.5 dark:bg-gray-600 dark:border-gray-500 dark:placeholder-gray-400 dark:text-white dark:focus:ring-primary-500 dark:focus:border-primary-500', required: true %>
  </div>

  <div class="col-span-2 sm:col-span-1">
    <%= form.label :national_health_card, class: 'block mb-2 text-sm font-medium text-gray-900 dark:text-white' %>
    <%= form.text_field :national_health_card, class: 'bg-gray-50 border border-gray-300 text-gray-900 text-sm rounded-lg focus:ring-primary-600 focus:border-primary-600 block w-full p-2.5 dark:bg-gray-600 dark:border-gray-500 dark:placeholder-gray-400 dark:text-white dark:focus:ring-primary-500 dark:focus:border-primary-500', required: true %>
  </div>

  <div class="col-span-2 sm:col-span-1">
    <%= form.label :email, class: 'block mb-2 text-sm font-medium text-gray-900 dark:text-white' %>
    <%= form.email_field :email, class: 'bg-gray-50 border border-gray-300 text-gray-900 text-sm rounded-lg focus:ring-primary-600 focus:border-primary-600 block w-full p-2.5 dark:bg-gray-600 dark:border-gray-500 dark:placeholder-gray-400 dark:text-white dark:focus:ring-primary-500 dark:focus:border-primary-500', required: true %>
  </div>

  <div class="col-span-2 sm:col-span-1">
    <%= form.label :birth_date, class: 'block mb-2 text-sm font-medium text-gray-900 dark:text-white' %>
    <%= form.date_field :birth_date, class: 'bg-gray-50 border border-gray-300 text-gray-900 text-sm rounded-lg focus:ring-primary-600 focus:border-primary-600 block w-full p-2.5 dark:bg-gray-600 dark:border-gray-500 dark:placeholder-gray-400 dark:text-white dark:focus:ring-primary-500 dark:focus:border-primary-500', required: true %>
  </div>

  <div class="col-span-2 sm:col-span-1">
    <%= form.label :phone_number, class: 'block mb-2 text-sm font-medium text-gray-900 dark:text-white' %>
    <%= form.telephone_field :phone_number, class: 'bg-gray-50 border border-gray-300 text-gray-900 text-sm rounded-lg focus:ring-primary-600 focus:border-primary-600 block w-full p-2.5 dark:bg-gray-600 dark:border-gray-500 dark:placeholder-gray-400 dark:text-white dark:focus:ring-primary-500 dark:focus:border-primary-500', required: true %>
  </div>

  <div class="col-span-2 sm:col-span-1">
    <%= form.label :status, class: 'block mb-2 text-sm font-medium text-gray-900 dark:text-white' %>
    <%= form.select :status, Municipe.statuses.keys, {}, class: 'bg-gray-50 border border-gray-300 text-gray-900 text-sm rounded-lg focus:ring-primary-600 focus:border-primary-600 block w-full p-2.5 dark:bg-gray-600 dark:border-gray-500 dark:placeholder-gray-400 dark:text-white dark:focus:ring-primary-500 dark:focus:border-primary-500', required: true %>
  </div>
</div>

app/views/municipes/_list.html.erb
<table class="w-full text-sm text-left rtl:text-right text-gray-500 dark:text-gray-400">
    <thead class="text-xs text-gray-700 uppercase bg-gray-50 dark:bg-gray-700 dark:text-gray-400">
    <tr>
      <th scope="col" class="px-6 py-3">Name</th>
      <th scope="col" class="px-6 py-3">CPF</th>
      <th scope="col" class="px-6 py-3">Date of Birth</th>
      <th scope="col" class="px-6 py-3">Health Card</th>
      <th scope="col" class="px-6 py-3">Phone</th>
      <th scope="col" class="px-6 py-3">Address</th>
      <th scope="col" class="px-6 py-3">Status</th>
      <th colspan="2"></th>
    </tr>
  </thead>
  <tbody class="odd:bg-white odd:dark:bg-gray-900 even:bg-gray-50 even:dark:bg-gray-800 border-b dark:border-gray-700">
    <% municipes.each do |municipe| %>
      <tr class="odd:bg-white odd:dark:bg-gray-900 even:bg-gray-50 even:dark:bg-gray-800 border-b dark:border-gray-700">
        <td scope="row" class="flex items-center p-4 mr-12 space-x-6 whitespace-nowrap">
          <%= display_municipe_photo(municipe, 'w-10 h-10 rounded-full' ) %>
            <div class="text-sm font-normal text-gray-500 dark:text-gray-400">
              <div class="text-base font-semibold text-gray-900 dark:text-white"><%= municipe.full_name %></div>
              <div class="text-sm font-normal text-gray-500 dark:text-gray-400"><%= municipe.email %></div>
            </div>
        </td>
        <td class="px-6 py-4"><%= municipe.cpf %></td>
        <td class="px-6 py-4"><%= municipe.birth_date %></td>
        <td class="px-6 py-4"><%= municipe.national_health_card %></td>
        <td class="px-6 py-4"><%= municipe.phone_number %></td>
        <td class="px-6 py-4"><%= render 'address_info', address: municipe.address %></td>
        <td class="px-6 py-4">
          <div class="flex items-center">
            <div class="h-2.5 w-2.5 rounded-full <%= municipe.active? ? 'bg-green-400' : 'bg-red-400' %> mr-2"></div>
            <%= municipe.status %>
          </div>
        </td>
        <td>
          <%= button_to municipe_path(municipe), method: :get, class: 'btn-primary', data: { turbo_frame: "drawer" } do %>
            <i class="bi bi-eyeglasses"></i>
            Show
          <% end %>
        </td>

        <td>
          <%= button_to edit_municipe_path(municipe), method: :get, class: 'btn-primary', data: { turbo_frame: "drawer" } do %>
            <i class="bi bi-pencil-square"></i>
            Edit
          <% end %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/municipes/_search_form.html.erb
<%= form_tag municipes_path, method: :get, data: { turbo_frame: "search-results",
                                            turbo_action: "advance", controller: "search",
                                            action: "input->search#submit" } do |f| %>
  <div class="relative">

    <div class="absolute inset-y-0 start-0 flex items-center ps-3 pointer-events-none">
      <svg class="w-4 h-4 text-gray-500 dark:text-gray-400" aria-hidden="true" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 20 20">
        <path stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="m19 19-4-4m0-7A7 7 0 1 1 1 8a7 7 0 0 1 14 0Z"/>
      </svg>
    </div>

    <%= text_field_tag "query", nil, placeholder: "Search with CPF, National Health Card or E-mail", class: "block w-full p-4 ps-10 text-sm text-gray-900 border border-gray-300
                                                                      rounded-lg bg-gray-50 focus:ring-blue-500 focus:border-blue-500 dark:bg-gray-700
                                                                      dark:border-gray-600 dark:placeholder-gray-400 dark:text-white
                                                                      dark:focus:ring-blue-500 dark:focus:border-blue-500" %>
    <%= submit_tag "Search", class: "text-white absolute end-2.5 bottom-2.5 bg-blue-700 hover:bg-blue-800 focus:ring-4 focus:outline-none
                                  focus:ring-blue-300 font-medium rounded-lg text-sm px-4 py-2 dark:bg-blue-600 dark:hover:bg-blue-700
                                  dark:focus:ring-blue-800" %>

  </div>
<% end %>

app/views/municipes/create.turbo_stream.erb
<%= turbo_stream.update("municipes", partial: "municipes/list", locals: { municipes: @municipes }) %>

<% if flash.keys.first == 'alert' || flash.keys.first == 'danger' %>
  <%= turbo_stream.append "flash", render_flash_messages %>
<% end %>

<%= turbo_stream.update "flash", render_flash_messages %>

app/views/municipes/edit.html.erb
<%= turbo_frame_tag "drawer" do %>
  <%= render(DrawerComponent.new(placement: "right", title: 'Update Municipe')) do %>
    <%= render 'form', municipe: @municipe %>
  <% end %>
<% end %>

app/views/municipes/index.html.erb
<div class="mt-4">
  <h1 class="text-center">Municipes</h1>

  <div class="flex justify-between items-center mt-5">
    <div class="w-1/2">
      <%= render partial: "search_form" %>
    </div>
    <div class="flex justify-end">
      <%= link_to 'New municipe', new_municipe_path,
                  method: :get,
                  class: "btn btn-primary ml-2",  data: {
                    turbo_frame: "drawer",
                    drawer_target: "drawer-right",
                    data_drawer: "right"
                  } %>
    </div>
  </div>

  <div id="drawer-right"
     class="fixed top-0 right-0 z-40 h-screen p-4 overflow-y-auto transition-transform translate-x-full bg-white w-120 dark:bg-gray-800"
     tabindex="-1" aria-labelledby="drawer-right-label">

    <h5 class="inline-flex items-center mb-6 text-sm font-semibold text-gray-500 uppercase dark:text-gray-400">  </h5>
  </div>

  <%= turbo_frame_tag 'search-results', target: '_top' do %>
    <div class="relative overflow-x-auto shadow-md sm:rounded-lg mt-5">
      <%= render partial: "municipes/list", locals: { municipes: @municipes } %>
    </div>

    <div class="flex mt-4">
      <div class="div flex-1">
        <%== pagy_nav(@pagy) %>
      </div>

      <div class="div flex-end mr-4">
        <%== pagy_info(@pagy) %>
      </div>
    </div>
  <% end %>

</div>

app/views/municipes/index.turbo_strem.erb
<%= turbo_stream.update "flash", render(FlashComponent.new(id: 'toast-success', type: 'success', message: flash.first.last)) %>

app/views/municipes/new.html.erb
<%= turbo_frame_tag "drawer" do %>
  <%= render(DrawerComponent.new(placement: "right", title: 'New Municipe')) do %>
    <%= render 'form', municipe: @municipe %>
  <% end %>
<% end %>

app/views/municipes/show.html.erb
<%= turbo_frame_tag "drawer" do %>
  <%= render(DrawerComponent.new(placement: "right", title: 'Show Municipe')) do %>
    <div class="p-4 md:p-5">
        <h5 class="inline-flex items-center mb-6 text-sm font-semibold text-gray-500 uppercase dark:text-gray-400"> General Information </h5>

        <p><strong>Name:</strong> <%= @municipe.full_name %></p>
        <p><strong>Email:</strong> <%= @municipe.email %></p>

        <h5 class="inline-flex items-center mb-6 text-sm font-semibold text-gray-500 uppercase dark:text-gray-400"> Address Information </h5>

        <p><strong>Street:</strong> <%= @municipe.address.street %></p>
      </div>
    </div>
  <% end %>
<% end %>

app/views/municipes/update.turbo_stream.erb
<%= turbo_stream.update("municipes", partial: "municipes/list", locals: { municipes: @municipes }) %>

<% if flash.keys.first == 'alert' || flash.keys.first == 'danger' %>
  <%= turbo_stream.append "flash", render_flash_messages %>
<% end %>

<%= turbo_stream.update "flash", render_flash_messages %>